### ISSUE TITLE
gmail api not working for some reason

### ISSUE THREAD

**Issue by proffapt** [proffapt/iitkgp-erp-login-pypi#17]
Getting the following error, whenever I generate a new `token.json`:

```python
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/iitkgp_erp_login/erp.py", line 189, in login
    otp = getOTP(OTP_CHECK_INTERVAL)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/iitkgp_erp_login/read_mail.py", line 20, in getOTP
    creds = generate_token()
            ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/iitkgp_erp_login/utils.py", line 73, in generate_token
    creds.refresh(Request())
  File "/opt/homebrew/lib/python3.11/site-packages/google/oauth2/credentials.py", line 335, in refresh
    ) = reauth.refresh_grant(
        ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/google/oauth2/reauth.py", line 351, in refresh_grant
    _client._handle_error_response(response_data, retryable_error)
  File "/opt/homebrew/lib/python3.11/site-packages/google/oauth2/_client.py", line 73, in _handle_error_response
    raise exceptions.RefreshError(
google.auth.exceptions.RefreshError: ('invalid_grant: Bad Request', {'error': 'invalid_grant', 'error_description': 'Bad Request'})
```

**Comment by proffapt** [comment]
It's not an issue in the code.
**Only the latest `token.json` file is valid.**

So, if you generate a new token file and try to use the old one.. this is what you will get.
